// @generated by `cargo run --example generate-types --manifest-path src-tauri/Cargo.toml`.
// Do not edit this file directly; change the Rust IPC declarations instead.

export type ActivityChange = { target: ActivityTarget, before?: ActivityGeometry, after?: ActivityGeometry, fields: Array<ActivityFieldChange>, };

export type ActivityFieldChange = { field: string, before: string, after: string, };

export type ActivityGeometry = { trackId?: string, startFrame: SafeInteger, durationFrames: SafeInteger, };

export type ActivityOrigin = "agent" | "user";

export type ActivityPhase = "running" | "awaiting_approval" | "queued" | "cancelling" | "completed" | "cancelled" | "failed";

export type ActivityTarget = { kind: ActivityTargetKind, id: string, trackId?: string, space?: ActivityTargetSpace, startFrame?: SafeInteger, endFrame?: SafeInteger, };

export type ActivityTargetKind = "project" | "asset" | "track" | "clip" | "text" | "transition";

export type ActivityTargetSpace = "timeline" | "source";

export type AgentActivity = { id: string, sequence: SafeInteger, origin: ActivityOrigin, projectId: string | null, generation: SafeInteger, runId?: string, toolCallId?: string, tool: string, action: string, label: string, phase: ActivityPhase, revision?: SafeInteger, transactionId?: string, changed: boolean, dryRun: boolean, targets: Array<ActivityTarget>, totalTargets: SafeInteger, changes: Array<ActivityChange>, jobIds: Array<string>, progress?: number, message?: string, error?: EditorError, };

export type AnalysisAction = { "action": "scenes", assetId: string, threshold?: number, } | { "action": "silence", assetId: string, };

export type AnalysisReply = { "kind": "scenes", "data": SceneAnalysisReply } | { "kind": "silence", "data": { assetId: string, intervals: Array<SilenceInterval>, } };

export type ArtifactKind = "master_video" | "proxy_video" | "pcm_audio" | "still_image" | "thumbnail" | "waveform" | "frame" | "transcript" | "other";

export type ArtifactRecord = { artifactId: string, cacheKey: string, kind: ArtifactKind, contentType: string, byteSize: SafeInteger, };

export type AspectRatio = "16:9" | "9:16" | "1:1";

export type AssetKind = "video" | "audio" | "stillImage";

export type AssetManifest = { id: string, kind: AssetKind, contentHash: string, original: OriginalMediaMetadata, normalization?: NormalizedAsset, };

export type AssistantAction = { "action": "status", } | { "action": "history", } | { "action": "prompt", text: string, } | { "action": "stop", } | { "action": "restart", } | { "action": "new_session", };

export type AssistantReply = { "action": "status", status: AssistantStatus, } | { "action": "history", messages: Array<SessionHistoryMessage>, } | { "action": "prompt", accepted: boolean, } | { "action": "stop", stopped: boolean, } | { "action": "restart", restarted: boolean, } | { "action": "new_session", created: boolean, };

export type AssistantStatus = { active: boolean, configured: boolean, providerId: string | null, modelId: string | null, sessionId: string | null, usage: AssistantUsage | null, };

export type AssistantUsage = { input: SafeInteger, output: SafeInteger, cacheRead: SafeInteger, cacheWrite: SafeInteger, total: SafeInteger, cost: number | null, };

export type AudioPlan = { sampleRate: number, channels: number, totalSamples: SafeInteger, segments: Array<AudioSegment>, };

export type AudioSegment = { clipId: string, trackId: string, assetId: string, artifactId: string, epochMs: number, activeStartSample: SafeInteger, activeEndSample: SafeInteger, startSample: SafeInteger, endSample: SafeInteger, sourceStartSample: SafeInteger, sourceEndSample: SafeInteger, gainDb: number, fadeInSamples: SafeInteger, fadeOutSamples: SafeInteger, transitionIn?: AudioTransition, transitionOut?: AudioTransition, };

export type AudioTransition = { id: string, side: AudioTransitionSide, startSample: SafeInteger, endSample: SafeInteger, };

export type AudioTransitionSide = "incoming" | "outgoing";

export type AuthType = "api_key" | "oauth";

export type BridgeEnvelope = { v: number, id: string, projectId: string | null, generation: SafeInteger, runId?: string, toolCallId?: string, } & ({ "kind": "request", method: string, params: unknown, } | { "kind": "response", ok: boolean,
/**
 * The transport envelope intentionally carries generic JSON so
 * private sidecar/auth responses do not become public editor types.
 * `EditorReply` is decoded and guarded only by the editor adapter.
 */
data?: unknown, error?: EditorError, } | { "kind": "event", event: string, data?: unknown, });

export type BridgeMessage = { "kind": "request", method: string, params: unknown, } | { "kind": "response", ok: boolean,
/**
 * The transport envelope intentionally carries generic JSON so
 * private sidecar/auth responses do not become public editor types.
 * `EditorReply` is decoded and guarded only by the editor adapter.
 */
data?: unknown, error?: EditorError, } | { "kind": "event", event: string, data?: unknown, };

export type CaptionProjection = { captionId: string, clipId: string, timelineStartFrame: SafeInteger, durationFrames: SafeInteger, sourceStartFrame: SafeInteger, };

export type ClipPatch = { fit?: FitMode, centerX?: number, centerY?: number, scale?: number, opacity?: number, gainDb?: number, audioEnabled?: boolean, fadeInFrames?: SafeInteger, fadeOutFrames?: SafeInteger, };

export type CreateGraphicRequest = { name: string, svg: string, width: number, height: number, };

export type DestRect = { x: number, y: number, width: SafeInteger, height: SafeInteger, };

export type EditOp = { "op": "set_project", name?: string, aspect?: AspectRatio, } | { "op": "add_track", id: string, kind: TrackKind, name: string, index: SafeInteger, } | { "op": "update_track", trackId: string, name?: string, muted?: boolean, locked?: boolean, } | { "op": "remove_track", trackId: string, deleteItems: boolean, } | { "op": "insert_clip", clip: MediaClip, } | { "op": "move_clip", clipId: string, trackId: string, startFrame: SafeInteger, } | { "op": "trim_clip", clipId: string, inFrame: SafeInteger, startFrame: SafeInteger, durationFrames: SafeInteger, } | { "op": "split_clip", clipId: string, frame: SafeInteger, rightClipId: string, } | { "op": "update_clip", clipId: string, patch: ClipPatch, } | { "op": "remove_clips", clipIds: Array<string>, } | { "op": "remove_range", startFrame: SafeInteger, endFrame: SafeInteger, ripple: boolean, } | { "op": "add_text", item: TextItem, } | { "op": "update_text", textId: string, patch: TextPatch, } | { "op": "remove_text", textId: string, } | { "op": "add_transition", leftClipId: string, rightClipId: string, durationFrames: SafeInteger, } | { "op": "remove_transition", transitionId: string, } | { "op": "replace_captions", clipId: string, transcriptId: string, style: TextStyle, };

export type EditResult = { transactionId: string, label: string, revision: SafeInteger, changed: boolean, affectedEntities: Array<EntityRef>, };

export type EditorError = { code: EditorErrorCode, message: string, details?: unknown, };

export type EditorErrorCode = "INVALID_ARGUMENT" | "REVISION_CONFLICT" | "IDEMPOTENCY_CONFLICT" | "STALE_SESSION" | "PERMISSION_DENIED" | "ASSET_UNAVAILABLE" | "MEDIA_UNSUPPORTED" | "JOB_CANCELLED" | "IO_ERROR" | "AUTH_REQUIRED" | "PROVIDER_ERROR" | "BUSY" | "SCHEMA_UNSUPPORTED";

export type EditorEvent = { kind: string, projectId: string | null, generation: SafeInteger, runId?: string, data?: unknown, };

export type EditorReply = { "kind": "project_status", "data": ProjectStatus } | { "kind": "project_snapshot", "data": ProjectSnapshot } | { "kind": "timeline_snapshot", "data": TimelineSnapshot } | { "kind": "project_edit", "data": EditResult } | { "kind": "project_history", "data": EditResult } | { "kind": "media", "data": MediaReply } | { "kind": "jobs", "data": JobsReply } | { "kind": "preview", "data": PreviewReply } | { "kind": "export_video", "data": ExportReply } | { "kind": "evidence", "data": EvidenceReply } | { "kind": "transcript", "data": EvidenceReply } | { "kind": "analyze_media", "data": EvidenceReply } | { "kind": "sample_frames", "data": EvidenceReply } | { "kind": "create_graphic", "data": EvidenceReply } | { "kind": "assistant", "data": AssistantReply } | { "kind": "providers", "data": ProvidersReply } | { "kind": "permissions", "data": PermissionsReply };

export type EditorRequest = { "method": "project_status", "params": Record<string, never> } | { "method": "project_create", "params": { name: string, aspect?: string, fpsNum?: SafeInteger, fpsDen?: SafeInteger, } } | { "method": "project_open", "params": Record<string, never> } | { "method": "project_save", "params": Record<string, never> } | { "method": "project_close", "params": Record<string, never> } | { "method": "project_snapshot", "params": Record<string, never> } | { "method": "timeline_snapshot", "params": Record<string, never> } | { "method": "timeline_selection", "params": { selection: TimelineSelection, } } | { "method": "project_history", "params": { action: string, expectedRevision: SafeInteger, expectedTransactionId?: string, } } | { "method": "edit_project", "params": { transactionId: string, expectedRevision: SafeInteger, label: string, operations: Array<EditOp>, dryRun?: boolean, } } | { "method": "media", "params": MediaAction } | { "method": "jobs", "params": JobsAction } | { "method": "preview", "params": PreviewAction } | { "method": "export_video", "params": ExportAction } | { "method": "evidence", "params": EvidenceAction } | { "method": "transcript", "params": TranscriptAction } | { "method": "analyze_media", "params": AnalysisAction } | { "method": "sample_frames", "params": SampleFramesRequest } | { "method": "create_graphic", "params": CreateGraphicRequest } | { "method": "assistant", "params": AssistantAction } | { "method": "providers", "params": ProvidersAction } | { "method": "permissions", "params": PermissionsAction };

export type EntityDelta = { entity: EntityRef, before?: EntityState, after?: EntityState,
/**
 * Array positions are part of an affected-entity delta because track and
 * clip order is meaningful. They are absent for document metadata.
 */
beforeIndex?: SafeInteger, afterIndex?: SafeInteger, };

export type EntityKind = "document" | "asset" | "track" | "clip" | "textItem" | "transition";

export type EntityRef = { kind: EntityKind, id: string, };

export type EntityState = { "kind": "document", "value": { name: string, profile: ProjectProfile, } } | { "kind": "asset", "value": AssetManifest } | { "kind": "track", "value": Track } | { "kind": "clip", "value": MediaClip } | { "kind": "textItem", "value": TextItem } | { "kind": "transition", "value": Transition };

export type EvidenceAction = { "action": "model_status", } | { "action": "transcribe", assetId: string, startFrame?: SafeInteger, endFrame?: SafeInteger, modelConsent: boolean, } | { "action": "read", transcriptId: string, } | { "action": "search", query: string, assetId?: string, } | { "action": "import_srt", playheadFrame: SafeInteger, style?: TextStyle, } | { "action": "export_srt", } | { "action": "scenes", assetId: string, threshold?: number, } | { "action": "silence", assetId: string, } | { "action": "sample_frames", assetId: string, startFrame: SafeInteger, endFrame: SafeInteger, count?: number, } | { "action": "create_graphic", name: string, svg: string, width: number, height: number, };

export type EvidenceGrantResult = { providerId: string, accountId: string, allowed: boolean, };

export type EvidenceReply = { "kind": "transcript", "data": TranscribeReply } | { "kind": "transcript_model_status", "data": SpeechModelInfo } | { "kind": "transcript_read", "data": Transcript } | { "kind": "transcript_search", "data": TranscriptSearchReply } | { "kind": "srt_imported", "data": SrtImportReply } | { "kind": "srt_exported", "data": SrtExportReply } | { "kind": "analysis", "data": AnalysisReply } | { "kind": "sample_frames", "data": SampleFramesReply } | { "kind": "graphic", "data": GraphicReply };

export type ExportAction = { "action": "start", revision: SafeInteger, resolution: 720 | 1080, srt: boolean, } | { "action": "status", jobId: string, } | { "action": "get", jobId: string, } | { "action": "progress", jobId: string, } | { "action": "cancel", jobId: string, } | { "action": "play", jobId: string, } | { "action": "show_file", jobId: string, };

export type ExportOpenReply = { job: JobSummary, destination: string, srtDestination?: string, };

export type ExportReply = { "kind": "started", "data": ExportStatus } | { "kind": "status", "data": ExportStatus } | { "kind": "cancelled", "data": ExportStatus } | { "kind": "played", "data": ExportOpenReply } | { "kind": "file_shown", "data": ExportOpenReply };

export type ExportResult = { revision: SafeInteger, planHash: string, resolution: SafeInteger, width: SafeInteger, height: SafeInteger, fpsNum: SafeInteger, fpsDen: SafeInteger, durationFrames: SafeInteger, hasAudio: boolean,
/**
 * This path is produced by the native save dialog and is only exposed
 * after FFmpeg and ffprobe have succeeded.
 */
destination: string, destinationIdentity: ExportTargetIdentity, srtDestination?: string, srtIdentity?: ExportTargetIdentity, };

export type ExportStatus = { job: JobSummary, result?: ExportResult, };

export type ExportTargetIdentity = { exists: boolean, size: SafeInteger, token: string, };

export type FileGrant = { grantId: string, scope: PermissionScope, path: string, identity: FileIdentity, purpose: FileGrantPurpose, createdAtMs: bigint, };

export type FileGrantPurpose = "import" | "relink" | "read" | "evidence" | "upload";

export type FileIdentity = { canonicalPath: string, token: string, size: SafeInteger, };

export type FitMode = "contain" | "cover";

export type FrameInterval = { startFrame: SafeInteger, durationFrames: SafeInteger, };

export type FrameRate = { num: SafeInteger, den: SafeInteger, };

export type GraphicReply = { assetId: string, revision: SafeInteger, name: string, width: number, height: number, artifact: ArtifactRecord, };

export type HistoryEntry = { transactionId: string, label: string, expectedRevision: SafeInteger, revision: SafeInteger, payloadHash: string, delta: TransactionDelta, result: EditResult, };

export type HistoryState = { undo: Array<HistoryEntry>, redo: Array<HistoryEntry>, };

export type ImportFailure = { path: string, error: EditorError, };

export type JobCancelReply = { job: JobSummary, };

export type JobGetReply = { job: JobSummary, resultAvailable: boolean, };

export type JobListReply = { jobs: Array<JobSummary>, };

export type JobPriority = "foreground" | "background";

export type JobState = "queued" | "running" | "completed" | "failed" | "cancelled";

export type JobSummary = { jobId: string, kind: string, priority: JobPriority, state: JobState, progress: number, generation: SafeInteger, projectId?: string, runId?: string, error?: EditorError, createdAtMs: SafeInteger, };

export type JobsAction = { "action": "list", } | { "action": "get", jobId: string, } | { "action": "cancel", jobId: string, };

export type JobsReply = { "kind": "list", "data": JobListReply } | { "kind": "get", "data": JobGetReply } | { "kind": "cancel", "data": JobCancelReply };

export type MediaAction = { "action": "list", } | { "action": "inspect", assetId: string, } | { "action": "import", paths?: Array<string>, } | { "action": "relink", assetId: string, } | { "action": "remove", assetId: string, } | { "action": "thumbnail", assetId: string, frame?: SafeInteger, } | { "action": "waveform", assetId: string, };

export type MediaArtifactReply = { assetId: string, artifact: ArtifactRecord, artifactUrl: string, };

export type MediaAssetReply = { assetId: string, removed: boolean, asset?: AssetManifest, jobId?: string, };

export type MediaClip = { id: string, trackId: string, assetId: string, startFrame: SafeInteger, inFrame: SafeInteger, durationFrames: SafeInteger, fit: FitMode, centerX: number, centerY: number, scale: number, opacity: number, gainDb: number, audioEnabled: boolean, fadeInFrames: SafeInteger, fadeOutFrames: SafeInteger, };

export type MediaImportReply = {
/**
 * Already-ready assets returned from content/profile dedupe. Newly
 * authorized media is represented by `job_ids` until completion.
 */
assets: Array<AssetManifest>, jobIds: Array<string>, failed: Array<ImportFailure>, };

export type MediaInspectReply = { asset: AssetManifest, identity: OriginalIdentity, originalAvailable: boolean, };

export type MediaListReply = { assets: Array<AssetManifest>, jobs: Array<JobSummary>, };

export type MediaReply = { "kind": "list", "data": MediaListReply } | { "kind": "inspect", "data": MediaInspectReply } | { "kind": "import", "data": MediaImportReply } | { "kind": "relink", "data": MediaAssetReply } | { "kind": "remove", "data": MediaAssetReply } | { "kind": "thumbnail", "data": MediaArtifactReply } | { "kind": "waveform", "data": MediaArtifactReply };

export type NormalizedAsset = { rendererVersion: string, epochMs: number, video?: NormalizedVideo, audio?: NormalizedAudio, };

export type NormalizedAudio = { pcmArtifactId: string, sampleCount: SafeInteger, sampleRate: number, channels: number, durationFrames: SafeInteger, activeStartSample: SafeInteger, activeEndSample: SafeInteger, sourceStartMs: number, sourceEndMs: number, };

export type NormalizedVideo = { masterArtifactId: string, proxyArtifactId?: string, frameCount: SafeInteger, width: number, height: number, fpsNum: number, fpsDen: number, activeStartFrame: SafeInteger, activeEndFrame: SafeInteger, sourceStartMs: number, sourceEndMs: number, proxyFrameCount?: SafeInteger, };

export type OriginalIdentity = { canonicalPath: string, byteSize: SafeInteger, modifiedTimeMs?: number, device?: SafeInteger, inode?: SafeInteger, contentHash: string, };

export type OriginalMediaMetadata = { fileName: string, location?: string, byteSize?: SafeInteger, modifiedTimeMs?: number, streams: Array<OriginalStreamMetadata>, };

export type OriginalStreamKind = "video" | "audio" | "other";

export type OriginalStreamMetadata = { kind: OriginalStreamKind, codec: string, durationMs?: SafeInteger, startTimeMs?: number, width: number | null, height: number | null, sampleRate: number | null, channels: number | null, rotationDegrees: number | null, sampleAspectNum: number | null, sampleAspectDen: number | null, colorSpace: string | null, colorTransfer: string | null, colorPrimaries: string | null, colorRange: string | null, };

export type PermissionDecision = { operationId: string, allow: boolean, };

export type PermissionDetails = { operation: PermissionOperation, path: string | null, paths: Array<string>, canonicalExecutable: string | null, arguments: Array<string>, cwd: string | null, url: string | null, method: string | null, bodySha256: string | null, bodyBytes: SafeInteger, targetIdentity: FileIdentity | null, offset: SafeInteger, length: SafeInteger, timeoutMs: SafeInteger, overwrite: boolean, };

export type PermissionOperation = "file_grant" | "system_read" | "system_write" | "system_execute" | "system_http" | "overwrite" | "upload";

export type PermissionRequest = { operationId: string, scope: PermissionScope, runId: string | null, toolCallId?: string, details: PermissionDetails, expiresAtMs: SafeInteger, };

export type PermissionScope = { workspaceId: string, projectId: string | null, generation: SafeInteger, };

export type PermissionsAction = { "action": "pending", "params": Record<string, never> } | { "action": "answer", "params": { operationId: string, allow: boolean, } } | { "action": "evidence", "params": { providerId: string, accountId: string, allow: boolean, } } | { "action": "revoke", "params": { providerId: string | null, accountId: string | null, } } | { "action": "grant_files", "params": { paths: Array<string> | null, purpose: FileGrantPurpose, } } | { "action": "system_read", "params": SystemReadRequest } | { "action": "system_write", "params": SystemWriteRequest } | { "action": "system_execute", "params": SystemExecuteRequest } | { "action": "system_http", "params": SystemHttpRequest };

export type PermissionsReply = { "kind": "pending", "data": Array<PermissionRequest> } | { "kind": "answer", "data": PermissionDecision } | { "kind": "evidence", "data": EvidenceGrantResult } | { "kind": "files", "data": Array<FileGrant> } | { "kind": "system_read", "data": SystemReadReply } | { "kind": "system_write", "data": SystemWriteReply } | { "kind": "system_execute", "data": SystemExecuteReply } | { "kind": "system_http", "data": SystemHttpReply };

export type PreviewAction = { "action": "plan", revision: SafeInteger, } | { "action": "render_frame", revision: SafeInteger, frame: SafeInteger, } | { "action": "render_audio_window", planHash: string, startSample: SafeInteger, sampleCount: SafeInteger, } | { "action": "seek", frame: SafeInteger, } | { "action": "play", } | { "action": "pause", } | { "action": "inspect", revision: SafeInteger, frames: SafeInteger[], };

export type PreviewAudioReply = { planHash: string, startSample: SafeInteger, sampleCount: SafeInteger, sampleRate: number, channels: number, artifactId: string, };

export type PreviewFrameReply = { revision: SafeInteger, frame: SafeInteger, planHash: string, artifactId: string, width: number, height: number, };

export type PreviewInspectFrame = { frame: SafeInteger, artifactId: string, };

export type PreviewReply = { "kind": "plan", "data": RenderPlan } | { "kind": "frame", "data": PreviewFrameReply } | { "kind": "audio", "data": PreviewAudioReply } | { "kind": "inspect", "data": { revision: SafeInteger, frames: Array<PreviewInspectFrame>, } } | { "kind": "ack", "data": { revision: SafeInteger, planHash: string, } };

export type PreviewTransportAction = "play" | "pause" | "seek";

export type PreviewTransportCommand = { sequence: SafeInteger, projectId: string, generation: SafeInteger, revision: SafeInteger, action: PreviewTransportAction, frame?: SafeInteger, };

export type PreviewTransportCompletion = { sequence: SafeInteger, projectId: string, generation: SafeInteger, error?: string, };

export type ProjectDocument = { projectId: string, name: string, revision: SafeInteger, profile: ProjectProfile, assets: Array<AssetManifest>, tracks: Array<Track>, clips: Array<MediaClip>, textItems: Array<TextItem>, transitions: Array<Transition>, };

export type ProjectEnvelope = { schemaVersion: number, document: ProjectDocument, history: HistoryState, receipts: Array<Receipt>, };

export type ProjectProfile = { width: number, height: number, fpsNum: number, fpsDen: number, background: RgbaColor, };

export type ProjectSnapshot = { document: ProjectDocument, workspaceId: string, };

export type ProjectStatus = { generation: SafeInteger, open: boolean, projectId?: string, workspaceId?: string, name?: string, revision?: SafeInteger, };

export type ProviderModel = { id: string, name: string, reasoning: boolean, input: Array<string>, contextWindow: SafeInteger, maxTokens: SafeInteger, };

export type ProviderStatus = { id: string, name: string, configured: boolean, authType: AuthType | null, modelCount: SafeInteger, };

export type ProvidersAction = { "action": "list", } | { "action": "models", providerId: string, } | { "action": "login", providerId: string, authType: AuthType, sessionOnly: boolean | null, } | { "action": "answer", promptId: string, value: string, } | { "action": "logout", providerId: string, } | { "action": "select", providerId: string, modelId: string, } | { "action": "refresh", };

export type ProvidersReply = { "action": "list", providers: Array<ProviderStatus>, selected: SelectedModel | null, } | { "action": "models", providerId: string, models: Array<ProviderModel>, } | { "action": "login", providerId: string, type: AuthType, configured: boolean, } | { "action": "answer", promptId: string, accepted: boolean, } | { "action": "logout", providerId: string, configured: boolean, } | { "action": "select", selected: SelectedModel, } | { "action": "refresh", refreshed: boolean, };

export type Receipt = { transactionId: string, payloadHash: string, result: EditResult, };

export type RenderLayer = { trackId: string, kind: RenderLayerKind, order: SafeInteger, segments: Array<RenderSegment>, transitions: Array<RenderTransition>, textOverlays: Array<RenderTextOverlay>, };

export type RenderLayerKind = "video" | "text";

export type RenderPlan = { rendererVersion: string, projectId: string, revision: SafeInteger, planHash: string, width: number, height: number, fpsNum: number, fpsDen: number, durationFrames: SafeInteger, background: RgbaColor, fontFamily: string,
/**
 * Content identity of the pinned Inter resources and rasterizer release.
 * It participates in the plan hash so preview/export cannot share pixels
 * produced by a different font resource.
 */
fontIdentity: string, fontWarning?: string, layers: Array<RenderLayer>, audio: AudioPlan, };

export type RenderSegment = { clipId: string, assetId: string, artifactId: string, epochMs: number, activeStartFrame: SafeInteger, activeEndFrame: SafeInteger, isStillImage: boolean, startFrame: SafeInteger, endFrame: SafeInteger, sourceStartFrame: SafeInteger, sourceEndFrame: SafeInteger, sourceWidth: number, sourceHeight: number, sourceRect: SourceRect, destRect: DestRect, opacity: number, fit: FitMode, centerX: number, centerY: number, scale: number, };

export type RenderTextOverlay = { id: string, trackId: string, ownerClipId?: string, startFrame: SafeInteger, endFrame: SafeInteger, sourceStartFrame?: SafeInteger, sourceDurationFrames?: SafeInteger, kind: TextKind, text: string, style: TextStyle, color: RgbaColor, fontSize: number, positionX: number, positionY: number, lineBreaks: SafeInteger[], lines: Array<string>,
/**
 * Required: a plan is not ready until the exact transparent PNG raster is
 * managed.  The Canvas and export paths consume this same artifact.
 */
rasterArtifactId: string, rasterSourceRect: SourceRect, rasterDestRect: DestRect, fontWarning?: string, };

export type RenderTransition = { id: string, trackId: string, leftClipId: string, rightClipId: string, startFrame: SafeInteger, endFrame: SafeInteger, durationFrames: SafeInteger, };

export type RgbaColor = { red: number, green: number, blue: number, alpha: number, };

export type SampleFrame = { assetId: string, frame: SafeInteger, sourceTimeMs: SafeInteger, artifactId: string, };

export type SampleFramesReply = { assetId: string, frames: Array<SampleFrame>, };

export type SampleFramesRequest = { assetId: string, startFrame: SafeInteger, endFrame: SafeInteger, count?: number, };

export type SceneAnalysisReply = { assetId: string, threshold: number, boundaries: Array<SceneBoundary>, };

export type SceneBoundary = { frame: SafeInteger, sourceTimeMs: SafeInteger, };

export type SelectedModel = { providerId: string, modelId: string, };

export type SessionHistoryMessage = { role: string, text: string, timestamp?: SafeInteger, toolName: string | null, isError: boolean | null, };

export type SilenceInterval = { assetId: string, startFrame: SafeInteger, endFrame: SafeInteger, startTimeMs: SafeInteger, endTimeMs: SafeInteger, };

export type SoftwarePreviewPacket = { generation: SafeInteger, projectId: string, revision: SafeInteger, planHash: string, frame: SafeInteger, sequence: SafeInteger, width: number, height: number, contentType: string, data: Uint8Array, };

export type SourceRect = { x: SafeInteger, y: SafeInteger, width: SafeInteger, height: SafeInteger, };

export type SpeechModelInfo = { version: string, commit: string, repository: string, revision: string, sourceUrl: string, file: string, expectedBytes: SafeInteger, sha256: string, available: boolean, downloadRequired: boolean, localOnly: boolean, };

export type SrtCue = { startTimeMs: SafeInteger, endTimeMs: SafeInteger, text: string, };

export type SrtExportReply = { contents: string, cueCount: number, };

export type SrtImportReply = { edit: EditResult, cueCount: number, };

export type SystemExecuteReply = { status: number | null, stdout: Array<number>, stderr: Array<number>, timedOut: boolean, };

export type SystemExecuteRequest = { executable: string, arguments: Array<string>, cwd: string, environment: { [key in string]?: string }, timeoutMs: SafeInteger, operationId: string | null, };

export type SystemHttpReply = { status: number, contentType: string | null, body: Array<number>, redirectUrl: string | null, };

export type SystemHttpRequest = { url: string, method: string, headers: { [key in string]?: string }, body: Array<number>, timeoutMs: SafeInteger, operationId: string | null, };

export type SystemReadReply = { path: string, offset: SafeInteger, data: Array<number>, eof: boolean, };

export type SystemReadRequest = { path: string, offset: SafeInteger, length: SafeInteger, operationId: string | null, };

export type SystemWriteReply = { path: string, bytesWritten: SafeInteger, };

export type SystemWriteRequest = { path: string, data: Array<number>, overwrite: boolean, operationId: string | null, };

export type TextItem = { id: string, trackId: string, kind: TextKind, text: string, style: TextStyle, color: RgbaColor, fontSize: number, positionX: number, positionY: number, lineBreaks: Array<number>, startFrame?: SafeInteger, durationFrames?: SafeInteger, ownerClipId?: string, sourceStartFrame?: SafeInteger, sourceDurationFrames?: SafeInteger, };

export type TextKind = "title" | "caption";

export type TextPatch = { text?: string, style?: TextStyle, color?: RgbaColor, fontSize?: number, positionX?: number, positionY?: number, lineBreaks?: Array<number>, startFrame?: SafeInteger, durationFrames?: SafeInteger, sourceStartFrame?: SafeInteger, sourceDurationFrames?: SafeInteger, };

export type TextStyle = "clean" | "boxed";

export type TimelineRange = { startFrame: SafeInteger, endFrame: SafeInteger, };

export type TimelineSelection = { clipIds: Array<string>, textIds: Array<string>, playheadFrame: SafeInteger, range?: TimelineRange, };

export type TimelineSnapshot = { revision: SafeInteger, durationFrames: SafeInteger, selection: TimelineSelection, document: ProjectDocument, };

export type Track = { id: string, kind: TrackKind, name: string, muted: boolean, locked: boolean, };

export type TrackKind = "video" | "audio" | "text";

export type TransactionDelta = { changes: Array<EntityDelta>, };

export type TranscribeReply = { transcript: Transcript, model: SpeechModelInfo, cached: boolean, approximateTiming: boolean, };

export type TranscribeRequest = { assetId: string, startFrame?: SafeInteger, endFrame?: SafeInteger,
/**
 * A missing/false value never starts a model download. The consent is
 * action-specific and is not persisted in the project document.
 */
modelConsent: boolean, };

export type Transcript = { transcriptId: string, assetId: string, sourceHash: string, segments: Array<TranscriptSpan>, };

export type TranscriptAction = { "action": "model_status", } | { "action": "transcribe", assetId: string, startFrame?: SafeInteger, endFrame?: SafeInteger, modelConsent: boolean, } | { "action": "read", transcriptId: string, } | { "action": "search", query: string, assetId?: string, } | { "action": "import_srt", playheadFrame: SafeInteger, style?: TextStyle, } | { "action": "export_srt", };

export type TranscriptSearchHit = { transcriptId: string, assetId: string, startFrame: SafeInteger, endFrame: SafeInteger, text: string, approximate: boolean, };

export type TranscriptSearchReply = { query: string, hits: Array<TranscriptSearchHit>, };

export type TranscriptSpan = { startFrame: SafeInteger, endFrame: SafeInteger, text: string, approximate: boolean, };

export type Transition = { id: string, leftClipId: string, rightClipId: string, durationFrames: SafeInteger, };

export type SafeInteger = number;

export type IpcEnvelopeBase = {
  v: 1,
  id: string,
  projectId: string | null,
  generation: SafeInteger,
  runId?: string,
  toolCallId?: string,
};

export type EditorRequestEnvelope = IpcEnvelopeBase & EditorRequest & {
  kind: "request",
};

export type EditorResponseSuccessEnvelope = IpcEnvelopeBase & {
  kind: "response",
  ok: true,
  data: EditorReply,
};

export type EditorResponseErrorEnvelope = IpcEnvelopeBase & {
  kind: "response",
  ok: false,
  error: EditorError,
};

export type EditorResponseEnvelope =
  | EditorResponseSuccessEnvelope
  | EditorResponseErrorEnvelope;

export type EditorEventEnvelope = IpcEnvelopeBase & {
  kind: "event",
  event: string,
  data?: unknown,
};

export type EditorEnvelope =
  | EditorRequestEnvelope
  | EditorResponseEnvelope
  | EditorEventEnvelope;
