use cutterhoochee_lib::ipc::{
    BridgeEnvelope, BridgeMessage, EditorEvent, EditorReply, EditorRequest,
};
use cutterhoochee_lib::media::evidence::SrtCue;
use cutterhoochee_lib::media::render::SoftwarePreviewPacket;
use cutterhoochee_lib::media::transcribe::TranscribeRequest;
use cutterhoochee_lib::project::model::{
    CaptionProjection, FrameInterval, FrameRate, ProjectEnvelope,
};
use std::any::TypeId;
use std::collections::HashSet;
use std::fs;
use std::path::PathBuf;
use ts_rs::{TypeVisitor, TS};

const ENVELOPE_ALIASES: &str = r#"export type SafeInteger = number;

export type IpcEnvelopeBase = {
  v: 1,
  id: string,
  projectId: string | null,
  generation: SafeInteger,
  runId?: string,
  toolCallId?: string,
};

export type EditorRequestEnvelope = IpcEnvelopeBase & EditorRequest & {
  kind: "request",
};

export type EditorResponseSuccessEnvelope = IpcEnvelopeBase & {
  kind: "response",
  ok: true,
  data: EditorReply,
};

export type EditorResponseErrorEnvelope = IpcEnvelopeBase & {
  kind: "response",
  ok: false,
  error: EditorError,
};

export type EditorResponseEnvelope =
  | EditorResponseSuccessEnvelope
  | EditorResponseErrorEnvelope;

export type EditorEventEnvelope = IpcEnvelopeBase & {
  kind: "event",
  event: string,
  data?: unknown,
};

export type EditorEnvelope =
  | EditorRequestEnvelope
  | EditorResponseEnvelope
  | EditorEventEnvelope;
"#;

fn exported_declaration(declaration: &str) -> String {
    declaration.strip_prefix("type ").map_or_else(
        || declaration.to_owned(),
        |body| format!("export type {body}"),
    )
}

#[derive(Default)]
struct DeclarationCollector {
    seen_types: HashSet<TypeId>,
    seen_names: HashSet<String>,
    declarations: Vec<(String, String)>,
}

impl TypeVisitor for DeclarationCollector {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.seen_types.insert(TypeId::of::<T>()) {
            return;
        }

        if T::output_path().is_some() {
            let name = T::ident();
            if self.seen_names.insert(name.clone()) {
                self.declarations
                    .push((name, exported_declaration(&T::decl())));
            }
        }

        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}

fn visit_ipc_roots(visitor: &mut DeclarationCollector) {
    visitor.visit::<EditorRequest>();
    visitor.visit::<EditorReply>();
    visitor.visit::<EditorEvent>();
    visitor.visit::<BridgeMessage>();
    visitor.visit::<BridgeEnvelope>();
}

/// Public types used by persistence and standalone editor APIs but not nested
/// under one of the transport envelope roots above.
fn visit_auxiliary_roots(visitor: &mut DeclarationCollector) {
    visitor.visit::<ProjectEnvelope>();
    visitor.visit::<FrameRate>();
    visitor.visit::<FrameInterval>();
    visitor.visit::<CaptionProjection>();
    visitor.visit::<SrtCue>();
    visitor.visit::<TranscribeRequest>();
    visitor.visit::<SoftwarePreviewPacket>();
    visitor.visit::<cutterhoochee_lib::activity::AgentActivity>();
    visitor.visit::<cutterhoochee_lib::media::render::PreviewTransportCommand>();
    visitor.visit::<cutterhoochee_lib::media::render::PreviewTransportCompletion>();
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let destination = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../shared/src/generated.ts");
    if let Some(parent) = destination.parent() {
        fs::create_dir_all(parent)?;
    }

    let mut collector = DeclarationCollector::default();
    visit_ipc_roots(&mut collector);
    visit_auxiliary_roots(&mut collector);
    collector
        .declarations
        .sort_unstable_by(|(left, _), (right, _)| left.cmp(right));

    let mut output = String::from(
        "// @generated by `cargo run --example generate-types --manifest-path src-tauri/Cargo.toml`.\n// Do not edit this file directly; change the Rust IPC declarations instead.\n\n",
    );
    for (_, declaration) in collector.declarations {
        output.push_str(&declaration);
        output.push_str("\n\n");
    }
    output.push_str(ENVELOPE_ALIASES);
    let normalized = output
        .trim_end()
        .lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n");
    fs::write(destination, format!("{normalized}\n"))?;
    Ok(())
}
